# Generated by Django 6.0.5 on 2026-05-31 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('abstract', models.TextField(help_text='Short description shown on the product card (max 300 characters).', max_length=300)),
                ('detailed_specifications', models.TextField(blank=True, help_text='Full specifications shown in the product detail modal.')),
                ('image_url', models.URLField(blank=True, help_text='URL to the product image (e.g. Firebase Storage link).')),
                ('is_color_printing', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='If unchecked, the product is hidden from the public catalog.')),
                ('is_in_stock', models.BooleanField(default=True, help_text='If unchecked, the product shows as "Out of Stock".')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
